spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test3
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
#    database-platform:
application:
  security:
    jwt:
      secret-key: 656e74657220796f7572207068726173652068657265
      expiration: 86400000 #a day
      refresh-token:
        expiration: 604800000 # 7 day

logging:
  level:
    org:
      springframework:
        security=DEBUG:
    web=DEBUG:
